class Locator(object):
    title = "//title"
    header = "//header"
    search_form = "//*[@class='input-area']"
    search_results = "//*[@class='output-area']"
    username = "//*[@id='username']"
    go_button = "//*[@class='submit']"
    status_text = "//*[@class='output-status-text']"
    repo_amount = "//*[@class='repo-amount']"
    repo_row = "//*[@class='repo-row'])"
    repo_name = "//*[@class='repo-row']//a[1]"
    repo_description = "//*[@class='repo-description'][1]"
    success_msg = "//*[@class='message-success']/strong"
    failure_msg = "//*[@class='message-failure']/strong"
